export const SET_ALERT = "SET_ALERT";
export const GET_ITEMS = "GET_ITEMS";

export const GET_COUNTRIES_REQUEST = "GET_COUNTRIES_REQUEST";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS"
export const GET_COUNTRIES_FAIL = "GET_COUNTRIES_FAIL";

export const CREATE_AUTHORS_REQUEST = "CREATE_AUTHORS_REQUEST";
export const CREATE_AUTHORS_SUCCESS = "CREATE_AUTHORS_SUCCESS";
export const CREATE_AUTHORS_FAIL = "CREATE_AUTHORS_FAIL";

export const GET_AUTHORS_REQUEST = "GET_AUTHORS_REQUEST";
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
export const GET_AUTHORS_FAIL = "GET_AUTHORS_FAIL";

export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAIL = "GET_BOOKS_FAIL";

export const CREATE_BOOKS_REQUEST = "CREATE_BOOKS_REQUEST";
export const CREATE_BOOKS_SUCCESS = "CREATE_BOOKS_SUCCESS";
export const CREATE_BOOKS_FAIL = "CREATE_BOOKS_FAIL";

export const GET_CATEOGORIES_REQUEST = "GET_CATEOGORIES_REQUEST";
export const GET_CATEOGORIES_SUCCESS = "GET_CATEOGORIES_SUCCESS";
export const GET_CATEOGORIES_FAIL = "GET_CATEOGORIES_FAIL";

export const CREATE_CATEOGORY_REQUEST = "CREATE_CATEOGORY_REQUEST";
export const CREATE_CATEOGORY_SUCCESS = "CREATE_CATEOGORY_SUCCESS";
export const CREATE_CATEOGORY_FAIL = "CREATE_CATEOGORY_FAIL";