export const GET_ITEMS = "GET_ITEMS";
export const GET_COUNTRIES_REQUEST = "GET_COUNTRIES_REQUEST";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS"
export const GET_COUNTRIES_FAIL = "GET_COUNTRIES_FAIL";
export const CREATE_AUTHORS_REQUEST = "CREATE_AUTHORS_REQUEST";
export const CREATE_AUTHORS_SUCCESS = "CREATE_AUTHORS_SUCCESS";
export const CREATE_AUTHORS_FAIL = "CREATE_AUTHORS_FAIL";