export const SET_ALERT = "SET_ALERT";
export const GET_ITEMS = "GET_ITEMS";

export const GET_COUNTRIES_REQUEST = "GET_COUNTRIES_REQUEST";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS"
export const GET_COUNTRIES_FAIL = "GET_COUNTRIES_FAIL";

export const CREATE_AUTHORS_REQUEST = "CREATE_AUTHORS_REQUEST";
export const CREATE_AUTHORS_SUCCESS = "CREATE_AUTHORS_SUCCESS";
export const CREATE_AUTHORS_FAIL = "CREATE_AUTHORS_FAIL";

export const GET_AUTHORS_REQUEST = "GET_AUTHORS_REQUEST";
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
export const GET_AUTHORS_FAIL = "GET_AUTHORS_FAIL";

export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAIL = "GET_BOOKS_FAIL";

export const CREATE_BOOKS_REQUEST = "CREATE_BOOKS_REQUEST";
export const CREATE_BOOKS_SUCCESS = "CREATE_BOOKS_SUCCESS";
export const CREATE_BOOKS_FAIL = "CREATE_BOOKS_FAIL";

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEOGRIES_FAIL";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";

export const CREATE_TAGS_REQUEST = "CREATE_TAGS_REQUEST";
export const CREATE_TAGS_SUCCESS = "CREATE_TAGS_SUCCESS";
export const CREATE_TAGS_FAIL = "CREATE_TAGS_FAIL";

export const GET_TAGS_REQUEST = "GET_TAGS_REQUEST";
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const GET_TAGS_FAIL = "GET_TAGS_FAIL";